# -*- coding: utf-8 -*-
"""index.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/pantelis/eng-ai-agents/blob/main/notebooks/assignments/devenv/index.ipynb

---
format:
    html:
        code-tools: true
    ipynb: default
jupyter: python3
---

## Development Environment Setup


### Ubuntu and MAC users

Install docker in your system and the VSCode docker and remote extensions.

### Windows users

1. Install [WSL2](https://learn.microsoft.com/en-us/windows/wsl/install).

2. Ensure that you also follow [this tutorial](https://learn.microsoft.com/en-us/windows/wsl/tutorials/wsl-vscode) to setup VSCode properly aka the VSCode can access the WSL2 filesystem and work with the [remote docker containers](https://learn.microsoft.com/en-us/windows/wsl/tutorials/wsl-containers).

3. If you have an NVIDIA GPU in your system, ensure you have [enabled it](https://learn.microsoft.com/en-us/windows/wsl/tutorials/gpu-compute).


### All Users

Following the instructions of the course site with respect to the [course docker container](https://github.com/pantelis/eng-ai-agents)

1. Install docker on your machine.
2. Clone the repo (For windows users ensure that you clone it on the WSL2 filesystem.) Show this by a screenshot below of the terminal where you have cloned the repo.
3. Build and launch the docker container **inside** your desired IDE (if you havent used an IDE before you can start with VSCode).
4. Launch the virtual environment with `make start` inside the container and then show a screenshot of your IDE and the terminal with the `(your virtual env)` prefix.
5. Select the kernel of your virtual environment (.venv folder) and execute the following code. Save the output of all cells of this notebook before submitting.
"""

import torch

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
if torch.cuda.is_available():
    print(torch.cuda.current_device())
    print(torch.cuda.device_count())
    print(torch.cuda.get_device_name(0))

device

